app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from logistics.views import HomePageView

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('summernote/', include('django_summernote.urls')),
    path('', HomePageView.as_view(), name="home"),
    path('login/', include('login.urls')),
    path('sale/', include('sale.urls')),
    path('purchase/', include('purchase.urls')),
    path('handbook/', include('handbook.urls')),
    path('logistics/', include('logistics.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

logistics/urls.py
from django.urls import path, include
from logistics.views import *


purchase_url = [
	path('update/<int:pk>/', WorkPurchaseUpdate.as_view(), name="work-purchase-update"),
	path('create/<int:pk>/', WorkPurchaseCreate.as_view(), name="work-purchase-create"),
	path('delete/<int:pk>/', WorkPurchaseDeleteView.as_view(), name="work-purchase-delete"),
	path('list/', WorkPurchaseList.as_view(), name="work-purchase-list"),

	path('upload/update/<int:pk>/', UploadPurchaseUpdate.as_view(), name="upload-purchase-update"),
	path('upload/list/', UploadPurchaseList.as_view(), name="upload-purchase-list"),

	path('path/list/', OnPathPurchaseList.as_view(), name="path-purchase-list"),
	path('path/update/<int:pk>/', OnPathPurchaseUpdate.as_view(), name="path-purchase-update"),

	path('click/<int:pk>/', ClickPurchaseDetail.as_view(), name="city-click-purchase"),
	# path('click/update/<int:pk>/', ClickPurchaseUpdate.as_view(), name="click-purchase-update"),
	path('click/list/', ClickPurchaseList.as_view(), name="click-purchase-list"),

	path('status-list/', StatusPurchaseList.as_view(), name="status-purchase-list"),

	path('all-data/', all_data_purchase, name="all_data_purshase"),

	path('city/<int:pk>/', ajax_click_purchase, name="ajax_click_purchase"),
	path('city-load/<int:pk>/', ajax_purchase, name="ajax_purchase"),

]

sale_url = [
	path('update/<int:pk>/', WorkSaleUpdate.as_view(), name="work-sale-update"),
	path('create/<int:pk>/', WorkSaleCreate.as_view(), name="work-sale-create"),
	path('delete/<int:pk>/', WorkSaleDeleteView.as_view(), name="work-sale-delete"),
	path('list/', WorkSaleList.as_view(), name="work-sale-list"),

	path('upload/update/<int:pk>/', UploadSaleUpdate.as_view(), name="upload-sale-update"),
	path('upload/list/', UploadSaleList.as_view(), name="upload-sale-list"),

	path('path/list/', OnPathSaleList.as_view(), name="path-sale-list"),
	path('path/update/<int:pk>/', OnPathSaleUpdate.as_view(), name="path-sale-update"),

	path('click/<int:pk>/', ClickSaleDetail.as_view(), name="city-click-sale"),
	# path('click/update/<int:pk>/', ClickSaleUpdate.as_view(), name="click-sale-update"),
	path('click/list/', ClickSaleList.as_view(), name="click-sale-list"),

	path('status-list/', StatusSaleList.as_view(), name="status-sale-list"),
	path('all-data/', all_data_sale, name="all_data_sale"),

	path('city/<int:pk>/', ajax_click_sale, name="ajax_click_sale"),
	path('city-load/<int:pk>/', ajax_sale, name="ajax_sale"),
]

urlpatterns = [
	path('purchase/', include(purchase_url)),
	path('sale/', include(sale_url)),
	# path('csv-response/', unruly_passengers_csv,)
]

purchase/urls.py
from django.urls import path

from purchase.views import *

urlpatterns = [
	path('list/', PurchaseListView.as_view(), name="purchase-bid-list"),
	path('<int:pk>/', PurchaseDetailView.as_view(), name="purchase-bid"),
	path('create/', PurchaseCreateView.as_view(), name="purchase-bid-create"),
	path('update/<int:pk>/', PurchaseUpdateView.as_view(), name="purchase-bid-update"),
	path('delete/<int:pk>/', PurchaseDeleteView.as_view(), name="purchase-bid-delete")
]

logistics/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

from handbook.models import OutPath, Transport, InPath, TradeTerm, Currency, Path, LogisticsProvider
from purchase.models import BidPurchase
from sale.models import BidSale


class StatusBidSale(models.Model):
	"""статус заявок от отдела сбыта"""
	bid = models.OneToOneField(
		BidSale,
		verbose_name="номер заявки",
		on_delete=models.CASCADE,
		related_name="bidsale",
		null=True
	)
	status = models.PositiveSmallIntegerField(verbose_name="статус заявки", default=0, blank=True)
	pub_date = models.DateField(
		verbose_name="Дата создания",
		auto_now_add=True,
		blank=True,
		null=True,
		editable=False
	)
	update_date = models.DateField(
		verbose_name="Дата изменения",
		auto_now=True,
		blank=True,
		null=True,
		editable=False
	)

	class Meta:
		verbose_name = "Статус заявки отдела сбыта"
		verbose_name_plural = "Статусы заявок отдела сбыта"
		ordering = ['-bid_id', '-status']

	def __str__(self):
		return f'{self.bid}'

	def get_absolute_url(self):
		return reverse('status-bid-sale', kwargs={'pk': self.pk})


class StatusBidPurchase(models.Model):
	"""статус заявок от отдела закупа"""
	bid = models.OneToOneField(
		BidPurchase,
		verbose_name="номер заявки",
		on_delete=models.CASCADE,
		related_name="bidpurchase",
		null=True
	)
	status = models.PositiveSmallIntegerField(verbose_name="статус заявки", default=0, blank=True)
	pub_date = models.DateField(
		verbose_name="Дата создания",
		auto_now_add=True,
		blank=True,
		null=True,
		editable=False
	)
	update_date = models.DateField(
		verbose_name="Дата изменения",
		auto_now=True,
		blank=True,
		null=True,
		editable=False
	)

	class Meta:
		verbose_name = "Статус заявки отдела закупа"
		verbose_name_plural = "Статусы заявок отдела закупа"
		ordering = ['-bid_id', '-status']

	def __str__(self):
		return f'{self.bid}'

	def get_absolute_url(self):
		return reverse('status-bid-purchase', kwargs={'pk': self.pk})


class WorkSale(models.Model):
	"""рабочая модель записями по заявке от сбыта(транспорт, маршрут и т.д.)"""
	created_by = models.ForeignKey(User, verbose_name="Сотрудник", on_delete=models.CASCADE, default=1, blank=True)
	bid = models.OneToOneField(
		StatusBidSale,
		verbose_name="номер заявки",
		related_name="statussale",
		on_delete=models.CASCADE,
	)
	way = models.ForeignKey(
		OutPath,
		verbose_name="код маршрута",
		on_delete=models.SET_NULL,
		blank=False,
		null=True,
	)
	price = models.PositiveIntegerField(verbose_name="цена услуги", blank=True, null=False)
	delta_price = models.PositiveIntegerField(verbose_name="новая цена", blank=True, default=0)
	currency = models.ForeignKey(Currency, verbose_name="Валюта", on_delete=models.CASCADE, default=1)
	"""добавляется при сохранении Upload"""
	num = models.CharField(
		verbose_name="номер машины",
		max_length=50,
		default="FF 0000 UZ"
	)

	path = models.ForeignKey(Path, verbose_name="Вид", on_delete=models.CASCADE, default=1)
	trade_term = models.ManyToManyField(TradeTerm, verbose_name="Торговые термины", related_name="term2")
	comment = models.TextField(
		verbose_name="Примечание",
		blank=True,
		default=""
	)
	provider = models.ForeignKey(LogisticsProvider, verbose_name="Поставщик услуг", on_delete=models.CASCADE)
	delivery_date = models.PositiveSmallIntegerField(verbose_name="Дни доставки", default=3)
	shipping_date = models.DateField(
		verbose_name="дата погрузки",
		editable=True,
		null=False,
		blank=False
	)
	pub_date = models.DateField(
		verbose_name="Дата создания",
		auto_now_add=True,
		editable=False,
		null=False,
		blank=True
	)
	update_date = models.DateField(
		verbose_name="Дата обновления",
		auto_now=True,
		editable=False,
		null=False,
		blank=True
	)

	class Meta:
		verbose_name = "обработка заявки отдела сбыта"
		verbose_name_plural = "обработка заявок отдела сбыта"
		ordering = ['-bid_id']

	def __str__(self):
		return f"{self.bid_id}"

	def get_absolute_url(self):
		return reverse('work-sale', kwargs={'pk': self.pk})


class WorkPurchase(models.Model):
	"""рабочая модель записями по заявке от закупа(транспорт, маршрут и т.д.)"""
	created_by = models.ForeignKey(User, verbose_name="Сотрудник", on_delete=models.CASCADE, default=1, blank=True)
	bid = models.OneToOneField(
		StatusBidPurchase,
		verbose_name="номер заявки",
		on_delete=models.CASCADE,
		related_name="statuspurchase",
		null=True,
		default="1"
	)
	way = models.ForeignKey(
		InPath,
		verbose_name="код маршрута",
		on_delete=models.SET_NULL,
		blank=False,
		null=True,
	)
	price = models.PositiveIntegerField(verbose_name="цена услуги", blank=True, default=0)
	currency = models.ForeignKey(Currency, verbose_name="Валюта", on_delete=models.CASCADE, default=1)
	delta_price = models.PositiveIntegerField(verbose_name="новая цена", blank=True, default=0, null=True)
	provider = models.ForeignKey(LogisticsProvider, verbose_name="Поставщик услуг", on_delete=models.CASCADE, default=1)

	trade_term = models.ManyToManyField(TradeTerm, verbose_name="Торговые термины", related_name="term")
	"""добавляется при сохранении Upload"""
	num = models.CharField(
		verbose_name="номер машины",
		max_length=50,
		blank=True,
		default="FF 0000 UZ"
	)
	comment = models.TextField(
		verbose_name="Примечание",
		blank=True,
		default=""
	)

	path = models.ForeignKey(Path, verbose_name="Вид", on_delete=models.CASCADE, default=1)
	delivery_date = models.PositiveSmallIntegerField(verbose_name="Дни доставки", default=3)
	shipping_date = models.DateField(
		verbose_name="дата погрузки",
		editable=True,
		null=True,
		blank=False
	)
	pub_date = models.DateField(
		verbose_name="Дата создания",
		auto_now_add=True,
		editable=False,
		null=True,
		blank=True
	)
	update_date = models.DateField(
		verbose_name="Дата обновления",
		auto_now=True,
		editable=False,
		null=True,
		blank=True
	)

	class Meta:
		verbose_name = "обработка заявки отдела закупа"
		verbose_name_plural = "обработка заявок отдела закупа"
		ordering = ['bid__bid_id']

	def __str__(self):
		return f"{self.bid_id}"

	def get_absolute_url(self):
		return reverse('work-purchase', kwargs={'pk': self.pk})


class WorkSaleDelete(models.Model):
	"""кто и когда удалил заявку"""
	info = models.CharField(verbose_name="info", max_length=200)
	date = models.DateTimeField(verbose_name="дата удаления", auto_now_add=True, blank=True)

	class Meta:
		verbose_name = "Удалил"
		verbose_name_plural = "Удалили"
		ordering = ['-date']

	def __str__(self):
		return f'{self.info}-{self.date}'


class WorkPurchaseDelete(models.Model):
	"""кто и когда удалил заявку"""
	info = models.CharField(verbose_name="info", max_length=200)
	date = models.DateTimeField(verbose_name="дата удаления", auto_now_add=True, blank=True)

	class Meta:
		verbose_name = "Удалил"
		verbose_name_plural = "Удалили"
		ordering = ['-date']

	def __str__(self):
		return f'{self.info}-{self.date}'


class OnUploadSale(models.Model):
	"""статус завки отдела сбыта на загрузке"""
	bid = models.OneToOneField(
		WorkSale,
		verbose_name="на загрузке",
		related_name="onupsale",
		on_delete=models.CASCADE,
		null=True
	)
	num = models.CharField(
		verbose_name="номер машины",
		max_length=50,
		default="FF 0000 UZ"
	)
	status = models.BooleanField(default=False, blank=True)
	pub_date = models.DateField(
		verbose_name="Дата создания",
		auto_now_add=True,
		editable=False,
		null=True,
		blank=True
	)
	update_date = models.DateField(
		verbose_name="Дата обновления",
		auto_now=True,
		editable=False,
		null=True,
		blank=True
	)
	status_path = models.BooleanField(default=False, blank=True)

	class Meta:
		verbose_name = "на загрузке - отдела сбыта"
		verbose_name_plural = "на загрузке - отдела сбыта"
		ordering = ['-bid__bid__id', '-status']

	def __str__(self):
		return f"{self.bid}"

	def get_absolute_url(self):
		return reverse('on-upload-sale', kwargs={'pk': self.pk})


class OnUploadPurchase(models.Model):
	"""статус завки отдела закупа на загрузке"""
	bid = models.OneToOneField(
		WorkPurchase,
		verbose_name="на загрузке",
		related_name="onuppurchase",
		on_delete=models.CASCADE,
		null=True
	)
	num = models.CharField(
		verbose_name="номер машины",
		max_length=50,
		default="FF 0000 UZ"
	)
	status = models.BooleanField(default=False, blank=True)
	pub_date = models.DateField(
		verbose_name="Дата создания",
		auto_now_add=True,
		editable=False,
		null=True,
		blank=True
	)
	update_date = models.DateField(
		verbose_name="Дата обновления",
		auto_now=True,
		editable=False,
		null=True,
		blank=True
	)
	status_path = models.BooleanField(default=False, blank=True)

	class Meta:
		verbose_name = "на загрузке - отдела закупа"
		verbose_name_plural = "на загрузке - отдела закупа"
		ordering = ['-bid__bid__id', '-status']

	def __str__(self):
		return f"{self.bid}"

	def get_absolute_url(self):
		return reverse('on-upload-purchase', kwargs={'pk': self.pk})


class OnPathSale(models.Model):
	"""статус завки отдела сбыта в пути"""
	bid = models.OneToOneField(
		WorkSale,
		verbose_name="в пути",
		related_name="onpathsale",
		on_delete=models.CASCADE,
		null=True
	)
	status = models.BooleanField(default=False, blank=True)
	pub_date = models.DateField(
		verbose_name="Дата создания",
		auto_now_add=True,
		editable=False,
		null=True,
		blank=True
	)
	update_date = models.DateField(
		verbose_name="Дата обновления",
		auto_now=True,
		editable=False,
		null=True,
		blank=True
	)
	status_path = models.BooleanField(default=False, blank=True)

	class Meta:
		verbose_name = "в пути - отдел сбыта"
		verbose_name_plural = "в пути - отдел сбыта"
		ordering = ['-bid__bid__id', '-status']

	def __str__(self):
		return f"{self.bid}"

	def get_absolute_url(self):
		return reverse('on-path-sale', kwargs={'pk': self.pk})


class OnPathPurchase(models.Model):
	"""статус завки отдела закупа в пути"""
	bid = models.OneToOneField(
		WorkPurchase,
		verbose_name="в пути",
		related_name="onpathpurchase",
		on_delete=models.CASCADE,

purchase/forms.py
from django import forms
from handbook.models import *
from purchase.models import BidPurchase


class BidPurchaseForm(forms.ModelForm):
	bid_number = forms.IntegerField(label="Номер заявки")
	cargo = forms.ModelMultipleChoiceField(queryset=Cargo.objects.all(), label="Груз")
	end_date = forms.CharField(label="Крайний срок")
	client = forms.ModelChoiceField(queryset=Provider.objects.all(), label="Поставщик")
	comment = forms.CharField(widget=forms.Textarea, max_length=200, label="Примечание")

	cargo.widget.attrs.update({'class': 'uk-select'})
	bid_number.widget.attrs.update({'class': 'uk-input'})
	end_date.widget.attrs.update({'class': 'uk-input'})
	client.widget.attrs.update({'class': 'uk-input'})
	comment.widget.attrs.update({'class': 'uk-textarea'})

	class Meta:
		model = BidPurchase
		exclude = (
			'created_by',
			'status',
			'pub_date',
			'update_date'
		)

purchase/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from logistics.models import StatusBidPurchase
from .forms import BidPurchaseForm
from .models import BidPurchase, PurchaseDelete


class PurchaseListView(PermissionRequiredMixin, ListView):
	model = BidPurchase
	paginate_by = 20
	template_name = 'purchase/purchase_list.html'
	permission_required = 'purchase.view_bidpurchase'
	login_url = 'login'
	ordering = ['-id']


class PurchaseDetailView(PermissionRequiredMixin, DetailView):
	model = BidPurchase
	template_name = 'purchase/purchase_detail.html'
	permission_required = 'purchase.view_bidpurchase'
	login_url = 'login'


class PurchaseCreateView(PermissionRequiredMixin, CreateView):
	model = BidPurchase
	form_class = BidPurchaseForm
	template_name = 'purchase/purchase_create.html'
	success_url = reverse_lazy('purchase-bid-list')
	permission_required = 'purchase.add_bidpurchase'
	login_url = 'login'

	def form_valid(self, form):
		form.instance.created_by = self.request.user
		StatusBidPurchase.objects.create(bid_id=form.save().id)
		return super(PurchaseCreateView, self).form_valid(form)


class PurchaseUpdateView(PermissionRequiredMixin, UpdateView):
	model = BidPurchase
	form_class = BidPurchaseForm
	success_url = reverse_lazy('purchase-bid-list')
	template_name = 'purchase/purchase_update.html'
	permission_required = 'purchase.add_bidpurchase'
	login_url = 'login'


class PurchaseDeleteView(PermissionRequiredMixin, DeleteView):
	model = BidPurchase
	success_url = reverse_lazy('purchase-bid-list')
	template_name = 'purchase/purchase_delete.html'
	permission_required = 'purchase.delete_bidpurchase'
	login_url = 'login'

	def delete(self, request, *args, **kwargs):
		"""
		Call the delete() method on the fetched object and then redirect to the
		success URL.
		"""
		self.object = self.get_object()
		success_url = self.get_success_url()
		info = f"{self.object.bid_number} {self.object.created_by.first_name}"
		PurchaseDelete.objects.create(info=info)
		self.object.delete()
		return HttpResponseRedirect(success_url)

logistics/templates/logistics/purchase/clickpurchase_detail.html
{% extends 'base/index.html' %}
{% load static %}
{% load my_tags %}

{% block title %}
    {{ object|verbose_name|upper }}
{% endblock %}

{% block main-content %}

    <h2>{{ object|verbose_name|upper }}</h2>
    {% if object.click_count == object.city_count %}
        <div class="uk-alert-danger" uk-alert>
            <a class="uk-alert-close" uk-close></a>
            <p>Заявка закрыта</p>
        </div>
    {% endif %}
    <div class="uk-margin">
        <a class="uk-button uk-button-default" href="{% url "click-purchase-list" %}">Назад</a>
    </div>
    <div class="uk-text-small uk-grid-small uk-child-width-1-6" uk-grid style="margin-left: 0px;">
        {% for item in auto %}

            <div id="s{{ item.sort }}" class="gray uk-card-hover ">

                    {{ item.city }}


                    {% if item.transport.id == 1 %}
                        <img src="{% get_media_prefix %}auto.png" width="50%" height="50%" uk-responsive
                             alt="{{ item.transport }}">
                    {% elif item.transport.id == 2 %}
                        <img src="{% get_media_prefix %}trayn.png" width="50%" height="50%" alt="{{ item.transport }}"
                             uk-responsive>
                    {% elif item.transport.id == 3 %}
                        <img src="{% get_media_prefix %}plan.png" width="50%" height="50%" alt="{{ item.transport }}"
                             uk-responsive>
                    {% elif item.transport.id == 4 %}
                        <img src="{% get_media_prefix %}sheep.png" width="50%" height="50%" uk-responsive
                             alt="{{ item.transport }}">
                    {% else %}
                        {{ item.transport }}
                    {% endif %}


            </div>

        {% endfor %}
    </div>
    <div class="uk-margin">
        <progress class="uk-progress" value="{{ object.click_count }}" max="{{ object.city_count }}"></progress>
    </div>
    <script>

        window.onload = function () {
            $.get("{% url "ajax_purchase" object.pk %}", function (data) {
                console.log(data);
                let idx = 1;
                while (idx <= data['id']) {
                    $('#s' + idx).removeClass('gray').toggleClass(data['class_css']);
                    idx += 1;
                };
            });
        };

    </script>

{% endblock %}

{% block ajax %}
    {% for item in auto %}
        $( document ).ready(function(){

        $("#s{{ item.sort }}").click(function() {
        $.ajax({
        url: '{% url "ajax_click_purchase" object.pk %}',
        data: {
        'id': {{ item.sort }}
        },
        method: 'GET',
        dataType: 'json',
        cache: false,
        success: function (data) {
        console.log(data['class_css']),
        alert("Изменено"),
        $('.uk-progress').val(data['click']),
        $('#s{{ item.sort }}').removeClass('gray').toggleClass(data['class_css'])
        },

        error: function (data) {
        if (data.yes) { alert("Ошибка!");}
        }
        });
        });
        });

    {% endfor %}
{% endblock %}

logistics/templates/logistics/purchase/statusbidpurchase_list.html
{% extends 'base/index.html' %}
{% load static %}
{% load my_tags %}

{% block title %}
    {% for object in object_list %}
        {% if forloop.first %}
            {{ object|verbose_name_plural|upper }}
        {% else %}
        {% endif %}

    {% endfor %}
{% endblock %}

{% block main-content %}
    {% for object in object_list %}
        {% if forloop.first %}
            <h3>{{ object|verbose_name_plural|upper }}</h3>
        {% else %}
        {% endif %}

    {% endfor %}
    <button class="uk-button uk-button-default uk-margin" id="excel">Скачать</button>
    <script src="{% static "/js/jquery2.min.js" %}"></script>
    <script src="{% static "/js/jquery.table2excel.min.js" %}"></script>
    <script type="text/javascript">
        $('#excel').click(function () {
            $(document).ready(function () {
                $("#exTable").table2excel({
                    filename: "Employees.xls"
                });
            });

        });
    </script>
    <form action="" method="GET">
        <div class="uk-fieldset" uk-grid>
            {% csrf_token %}
            {% for field in form %}
                {% if field.is_hidden %}
                    {{ field }}
                {% else %}
                    <div class="uk-margin">
                        <label class="uk-form-label">
                            {{ field.label }}
                        </label>
                        <div class="uk-form-controls">

                            {% if field.errors %}
                                <div class="uk-alert-danger">
                                    {{ field.errors }}
                                </div>
                            {% endif %}

                            {{ field }}
                        </div>
                    </div>
                {% endif %}

            {% endfor %}
        </div>
        <div class="uk-margin">
            <input class="uk-button uk-button-default" value="Отправить" type="submit">
        </div>
        <script>
            flatpickr("#id_min_pub_date", {
                altInput: true,
                altFormat: "F j, Y",
                dateFormat: "Y-m-d",
                "locale": "ru",
            });
            flatpickr("#id_max_pub_date", {
                altInput: true,
                altFormat: "F j, Y",
                dateFormat: "Y-m-d",
                "locale": "ru",
            });
            flatpickr("#id_min_end_date", {
                altInput: true,
                altFormat: "F j, Y",
                dateFormat: "Y-m-d",
                "locale": "ru",
            });
            flatpickr("#id_max_end_date", {
                altInput: true,
                altFormat: "F j, Y",
                dateFormat: "Y-m-d",
                "locale": "ru",
            });
        </script>
    </form>
    <div class="uk-overflow-auto">
        <table class="uk-table uk-table-divider uk-table-striped uk-table-hover" id="exTable">
            <thead>
            <tr>
                <th>№ заявки</th>
                <th>№ SAP</th>
                <th>Клиент/Поставщик</th>
                <th>Материал</th>
                <th>Примечание</th>
                <th>Дата открытия</th>
                <th>Когда нужен транспорт</th>
                <th>Статус</th>
                <th>Файл</th>
                <th>Заявитель</th>
            </tr>
            </thead>
            <tbody>
            {% for bid in object_list %}
                <tr>
                    {% if bid.bid.status %}
                        <td>
                            {{ bid.bid.id }}
                        </td>
                    {% else %}
                        {% if perms.logistics.add_worksale %}
                            <td class="uk-table-link">
                                <a href="{% url "work-purchase-create" bid.bid_id %}">
                                    {{ bid.bid.id }}
                                </a>
                            </td>

                        {% else %}
                            <td>
                                {{ bid.bid.id }}
                            </td>
                        {% endif %}

                    {% endif %}
                    <td>{{ bid.bid.bid_number }}</td>
                    <td>{{ bid.bid.client }}</td>
                    <td>
                        {% for cargo in bid.bid.cargo.all %}
                            {{ cargo }}
                        {% endfor %}
                    </td>
                    <td>{{ bid.bid.comment }}</td>
                    <td>{{ bid.bid.pub_date }}</td>
                    <td>{{ bid.bid.end_date }}</td>
                    <td>
                        {% if bid.status == 1 %}
                            <span class="uk-text-success">принята</span>
                        {% elif bid.status == 2 %}
                            <span class="uk-text-success">на загрузке</span>
                        {% elif bid.status == 3 %}
                            <span class="uk-text-success">в пути</span>
                        {% elif bid.status == 4 %}
                            <span class="uk-text-success">закрыта</span>
                        {% else %}
                            <span class="uk-text-danger">не принята</span>
                        {% endif %}
                    </td>
                    <td class="uk-table-link">
                        <a href="{% get_media_prefix %}{{ bid.bid.file }}" alt="файл" target="_blank">
                            {{ bid.bid.file }}
                        </a>
                    </td>
                    <td>{{ bid.bid.created_by.first_name }} {{ bid.bid.created_by.last_name }}</td>
                </tr>
            {% empty %}
                Нет данных
            {% endfor %}
            </tbody>
        </table>
    </div>
    {% include "base/paginator-list.html" with page=object_list %}

{% endblock %}

logistics/templates/logistics/purchase/workpurchase_create.html
{% extends 'base/index.html' %}
{% load static %}
{% load my_tags %}
{% block title %}
Создание заявки
{% endblock %}
{% block main-content %}
    <h3>Создание заявки</h3>
    <div class="uk-margin">
    <a class="uk-button uk-button-default" href="{% url "work-purchase-list" %}">Назад</a>
    </div>
    <div class="uk-child-width-1-2@m" uk-grid>
        <form method="post" class="uk-form-stacked" enctype="multipart/form-data">
            <fieldset class="uk-fieldset">
                {% csrf_token %}
                {% for field in form %}
                    {% if field.is_hidden %}
                        {{ field }}
                    {% else %}
                        <div class="uk-margin">
                            <label class="uk-form-label">
                                {{ field.label }}
                            </label>
                            <div class="uk-form-controls">

                                {% if field.errors %}
                                    <div class="uk-alert-danger">
                                        {{ field.errors }}
                                    </div>
                                {% endif %}

                                {{ field }}
                            </div>
                        </div>
                    {% endif %}

                {% endfor %}

                <div class="uk-margin">
                    <input class="uk-button uk-button-default" value="Отправить" type="submit">
                </div>
            </fieldset>
            <script>
                flatpickr("#id_shipping_date", {
                    altInput: true,
                    altFormat: "F j, Y",
                    dateFormat: "Y-m-d",
                    minDate: "today",
                    "locale": "ru",
                });
            </script>
        </form>


        <div>
            <h3>Форма заполнения заявки</h3>
            <ul class="uk-list uk-list-divider">
                <li>Укажите номер входящего маршрута</li>
                <li>Укажите цену услуги</li>
                <li>Укажите валюту</li>
                <li>Укажите транспорт</li>
                <li>Укажите торговые термины</li>
                <li>Укажите дни поставки</li>
                <li>Укажите дату начала погрузки</li>
            </ul>
        </div>
    </div>
{% endblock %}