app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from logistics.views import HomePageView

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('summernote/', include('django_summernote.urls')),
    path('', HomePageView.as_view(), name="home"),
    path('login/', include('login.urls')),
    path('sale/', include('sale.urls')),
    path('purchase/', include('purchase.urls')),
    path('handbook/', include('handbook.urls')),
    path('logistics/', include('logistics.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

purchase/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

from handbook.models import Client, Cargo, Provider


class BidPurchase(models.Model):
	""""заявка отдела закупа"""
	created_by = models.ForeignKey(
		User,
		verbose_name="Заявитель",
		on_delete=models.PROTECT,
		null=True,
		related_name="cargoes"
	)
	bid_number = models.PositiveIntegerField(
		verbose_name="Номер заявки",
		default=1234567
	)
	cargo = models.ManyToManyField(
		Cargo,
		verbose_name="Грузы",
		related_name="cargoes2",
	)
	end_date = models.DateField(
		verbose_name="Крайний срок",
		blank=False,
		null=True
	)
	client = models.ForeignKey(
		Provider,
		verbose_name="поставщик",
		on_delete=models.PROTECT,
		null=True
	)
	comment = models.TextField(
		verbose_name="Примечание",
		blank=True,
		default=""
	)
	pub_date = models.DateField(
		verbose_name="Дата создания",
		auto_now_add=True,
		blank=True,
		null=True,
		editable=False
	)
	update_date = models.DateField(
		verbose_name="Дата изменения",
		auto_now=True,
		blank=True,
		null=True,
		editable=False
	)
	file = models.FileField(
		verbose_name="Файл",
		upload_to="uploads/%Y/%m/%d/",
		blank=True,
		default="",
		max_length=100,
	)
	status = models.BooleanField(verbose_name="Статус", default=False, blank=True)

	class Meta:
		verbose_name = "Заявка отдела закупа"
		verbose_name_plural = "Заявки отдела закупа"
		ordering = ['-id']

	def __str__(self):
		return f"{self.bid_number}"

	def get_absolute_url(self):
		return reverse('purchase-bid', kwargs={'pk': self.pk})


class PurchaseDelete(models.Model):
	"""кто и когда удалил заявку"""
	info = models.CharField(verbose_name="info", max_length=200)
	date = models.DateTimeField(verbose_name="дата удаления", auto_now_add=True, blank=True)

	class Meta:
		verbose_name = "Удалил"
		verbose_name_plural = "Удалили"
		ordering = ['-date']

	def __str__(self):
		return f'{self.info}-{self.date}'

sale/models.py
from django.db import models
from django.contrib.auth.models import User

from handbook.models import *


class BidSale(models.Model):
	"""заявка отдела сбыта"""
	created_by = models.ForeignKey(
		User,
		verbose_name="Заявитель",
		on_delete=models.PROTECT,
		null=True
	)
	bid_number = models.PositiveIntegerField(
		verbose_name="Номер заявки",
		default=1234567
	)
	cargo = models.ManyToManyField(
		Cargo,
		verbose_name="Грузы",
		related_name="cargoes"
	)
	end_date = models.DateField(
		verbose_name="Крайний срок",
		blank=False,
		null=True
	)
	client = models.ForeignKey(
		Client,
		verbose_name="клиент",
		on_delete=models.PROTECT,
		null=True
	)
	comment = models.TextField(
		verbose_name="Примечание",
		blank=True,
		default=""
	)
	pub_date = models.DateField(
		verbose_name="Дата создания",
		auto_now_add=True,
		blank=True,
		null=True,
		editable=False
	)
	update_date = models.DateField(
		verbose_name="Дата изменения",
		auto_now=True,
		blank=True,
		null=True,
		editable=False
	)
	file = models.FileField(
		verbose_name="Файл",
		upload_to="uploads/%Y/%m/%d/",
		blank=True,
		default="",
		max_length=100,
	)
	status = models.BooleanField(verbose_name="Статус", default=False, blank=True)

	class Meta:
		verbose_name = "Заявка отдела сбыта"
		verbose_name_plural = "Заявки отдела сбыта"
		ordering = ['-id']

	def __str__(self):
		return f"{self.bid_number}"

	def get_absolute_url(self):
		return reverse('sale-bid', kwargs={'pk': self.pk})


class SaleDelete(models.Model):
	"""кто и когда удалил заявку"""
	info = models.CharField(verbose_name="info", max_length=200)
	date = models.DateTimeField(verbose_name="дата удаления", auto_now_add=True, blank=True)

	class Meta:
		verbose_name = "Удалил"
		verbose_name_plural = "Удалили"
		ordering = ['-date']

	def __str__(self):
		return f'{self.info}-{self.date}'

templates/base/footer.html
{% load static %}
<div class="uk-section uk-margin-medium-top uk-background-cover"  style="background-image: url({% get_media_prefix %}logo/block-top-bg.png);">
    <div class="uk-container">

        <h3>Приложение для формирования заявок</h3>

        <div class="uk-grid-match uk-child-width-1-2@m uk-child-width-1-1@s" uk-grid>
            <div class="uk-width-1-5@l uk-width-1-1@s">
                <img src="{% get_media_prefix %}logo/logo320.png" alt="SAG" width="25%" uk-responsive>
            </div>
            <div class="uk-width-expand@l uk-width-1-1@s">
                <p>Маркетинг лучший друг логистики. Маркетинг и логистика - это основа всего бизнеса. Если правильно выбран товар, рынок и логистические каналы, то отделу продаж отводится чисто техническая роль по заключению договоров с клиентами.</p>
                <p></p>
            </div>
        </div>

    </div>
</div>

templates/base/head.html
{% load static %}
<link rel="stylesheet" href="{% static '/css/uikit.min.css' %}">

<script type="text/javascript" src="{% static 'js/loader.js' %}"></script>

<link href="{% static '/css/css/fontawesome.css' %}" rel="stylesheet">
<link href="{% static '/css/css/brands.css' %}" rel="stylesheet">
<link href="{% static '/css/css/solid.css' %}" rel="stylesheet">

<link rel="stylesheet" href="{% static '/css/flatpickr.min.css' %}">
    <script src="{% static '/css/flatpickr.min.js' %}"></script>
    <script src="{% static '/css/ru.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static '/css/material_blue.css' %}">

<style>
    .green {
        border-left: 6px solid green;
        height: inherit;
        left: 50%;
        margin-left: -3px;
        top: 0;
    }
    .orange {
    border-left: 6px solid orange;
    height: inherit;
    left: 50%;
    margin-left: -3px;
    top: 0;
}
    .red {
    border-left: 6px solid red;
    height: inherit;
    left: 50%;
    margin-left: -3px;
    top: 0;
}
    .gray {
    border-left: 6px solid gray;
    height: inherit;
    left: 50%;
    margin-left: -3px;
    top: 0;
}

</style>

templates/base/index.html
<!DOCTYPE html>{% load static %}
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="author" content="RDev">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0"/>
    <link rel="icon" type="image/png" href="{% get_media_prefix %}logo/logo64.png">
    <title>{% block title %}{% endblock %}</title>
    {% include "base/head.html" %}
</head>
<body>
{% include "base/menu.html" %}
<div class="uk-container">
    {% if user.is_authenticated %}
        {% block main-content %}

        {% endblock %}
    {% else %}
        <div class="uk-alert-danger" uk-alert>
            <a class="uk-alert-close" uk-close></a>
            <h3>Вы не авторизовались в системе!</h3>
            <a href="{% url 'login' %}" class="uk-button-default uk-button">Авторизоваться</a>
        </div>
    {% endif %}
</div>
{% include "base/footer.html" %}
{% include "base/js.html" %}

{% block modal %}
{% endblock %}

<script>
    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });

    {% block ajax %}



    {% endblock %}
</script>

</body>
</html>

templates/base/js.html
{% load static %}

<script src="{% static 'js/uikit.js' %}"></script>
<script src="{% static 'js/uikit-icons.js' %}"></script>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery.table2excel.min.js' %}"></script>



{#<script>#}
{#    $("#data").change(function () {#}
{#        var email = $(this).val();#}
{##}
{#        $.ajax({#}
{#            url: '/handbook/country-list/',#}
{#            data: {#}
{#                'email': email#}
{#            },#}
{#            dataType: 'json',#}
{#            success: function (data) {#}
{#                if (data.yes) {#}
{#                    alert("Пользователь с таким email уже существует!");#}
{#                }#}
{#            }#}
{#        });#}
{##}
{#    });#}
{#</script>#}

templates/base/menu.html
<nav class="uk-navbar-container uk-margin-medium-bottom" uk-navbar uk-sticky>
    <div class="uk-navbar-left">

        <ul class="uk-navbar-nav">
            <li class="uk-active uk-margin-left">
                <a href="#" uk-toggle="target: #offcanvas-nav">
                    <span uk-navbar-toggle-icon></span>
                    <span class="uk-margin-small-left">Меню</span>
                </a>
            </li>
            <li>
                <a href="{% url 'home' %}">Главная</a>
            </li>
        </ul>

    </div>

    <div class="uk-navbar-right">

        {#        <div class="">#}
        {#            <form class="uk-search uk-search-default" method="get">#}
        {##}
        {#                <input class="uk-search-input" type="search" name="order_number" placeholder="Найти заявку...">#}
        {#                <input type="submit" value="Найти заявку...">#}
        {#            </form>#}
        {#        </div>#}

        <ul class="uk-navbar-nav uk-margin-right">
            <li><a href="">{{ request.user.first_name }} {{ request.user.last_name }}</a></li>
            <li class="uk-active "><a href="{% url "logout" %}" uk-icon="icon: reply"></a></li>
        </ul>

    </div>
</nav>

<div id="offcanvas-nav" uk-offcanvas="mode: push; overlay: true">
    <div class="uk-offcanvas-bar">
        <ul class="uk-nav-default uk-nav-parent-icon" uk-nav>
            <li class="uk-parent uk-active">
                <a href="#">
                    <span class="uk-margin-small-right" uk-icon="icon: yelp"></span>
                    Статистика
                </a>
                <ul class="uk-nav-sub">
                    {% if perms.purchase.add_bidpurchase or perms.logistics.add_cityclickpurchase %}
                        <li><a href="{% url "all_data_purshase" %}">Закуп</a></li>
                    {% endif %}
                    {% if perms.sale.add_bidsale or perms.logistics.add_cityclickpurchase %}
                        <li><a href="{% url "all_data_sale" %}">Сбыт</a></li>
                    {% endif %}
                </ul>
            </li>
            <li class="uk-nav-divider"></li>
            <li class="uk-parent">
                <a href="#"><span class="uk-margin-small-right" uk-icon="icon: cart"></span> Заявки отдел закупа</a>
                <ul class="uk-nav-sub">
                    <li>
                        <a href="{% url "purchase-bid-list" %}">
                            <span class="uk-margin-small-right" uk-icon="icon: list">
                            </span>
                            Заявки отдела
                        </a>
                    </li>
                    <li>
                        <a href="{% url "purchase-bid-create" %}">
                            <span class="uk-margin-small-right" uk-icon="icon: plus">
                            </span>
                            Подать заявку
                        </a>
                    </li>
                    <li>
                        <a href="{% url "status-purchase-list" %}">
                            <span class="uk-margin-small-right" uk-icon="icon: play"></span>
                            Статусы заявок
                        </a>
                    </li>
                </ul>
            </li>
            <li class="uk-nav-divider"></li>
            <li class="uk-parent">
                <a href="#"><span class="uk-margin-small-right" uk-icon="icon: tag"></span> Заявки отдел сбыта</a>
                <ul class="uk-nav-sub">
                    <li>
                        <a href="{% url "sale-bid-list" %}">
                            <span class="uk-margin-small-right" uk-icon="icon: list">
                            </span>
                            Заявки отдела
                        </a>
                    </li>
                    <li>
                        <a href="{% url "sale-bid-create" %}">
                            <span class="uk-margin-small-right" uk-icon="icon: plus">
                            </span>
                            Подать заявку
                        </a>
                    </li>
                    <li>
                        <a href="{% url "status-sale-list" %}">
                            <span class="uk-margin-small-right" uk-icon="icon: play"></span>
                            Статусы заявок
                        </a>
                    </li>
                </ul>
            </li>
            <li class="uk-nav-divider"></li>
            <li class="uk-parent">
                <a href="#"><span class="uk-margin-small-right" uk-icon="icon: database"></span> Справочник</a>
                <ul class="uk-nav-sub">
                    <li><a href="{% url "cargo" %}"> Материалы</a></li>
                    <li><a href="{% url "client_list" %}"> Клиенты</a></li>
                    <li><a href="{% url "provider" %}"> Поставщики</a></li>
                    <li><a href="{% url "trade-term" %}"> Товарные термины</a></li>
                    <li><a href="{% url "city" %}"> Города</a></li>
                    <li><a href="{% url "in-path" %}"> Коды входящих маршрутов</a></li>
                    <li><a href="{% url "out-path" %}"> Коды исходящих маршрутов</a></li>
                    <li><a href="{% url "currency" %}"> Валюта</a></li>
                    <li><a href="{% url "transport" %}"> Транспорт</a></li>
                    <li><a href="{% url "logistics-provider" %}"> Поставщик услуг для лог.</a></li>
                    <li><a href="{% url "path" %}"> Вид маршрута</a></li>
                    <!--<li><a href="{% url "status" %}"> Вид маршрута</a></li>-->
                </ul>
            </li>
            <li class="uk-nav-divider"></li>
            <li class="uk-parent">
                <a href="#"><span class="uk-margin-small-right" uk-icon="icon: code"></span> Отдел логистики</a>
                <ul class="uk-nav-sub">
                    <li>
                        <a href="{% url "status-purchase-list" %}">
                            <span class="uk-margin-small-right" uk-icon="icon: list"></span>
                            Обработка заявок отдела закупа
                        </a>

                    </li>
                    <li>
                        <a href="{% url "status-sale-list" %}">
                            <span class="uk-margin-small-right" uk-icon="icon: list"></span>
                            Обработка заявок отдела сбыта
                        </a>
                    </li>
                    <li class="uk-nav-divider"></li>
                    <li class="uk-nav-divider"></li>
                    <li class="uk-parent">
                        <a class="uk-text-uppercase" href="#">
                            <span class="uk-margin-small-right" uk-icon="icon: shrink"></span>
                            Работа с входящими заявками
                        </a>
                        <ul class="uk-nav-sub">
                            <li class="uk-nav-divider"></li>
                            <li><a class="uk-text-danger" href="{% url "work-purchase-list" %}">
                                <span class="uk-margin-small-right" uk-icon="icon: shrink"></span>
                                Заявки в обработке
                            </a>
                            </li>
                            <li><a class="uk-text-warning" href="{% url "upload-purchase-list" %}">
                                <span class="uk-margin-small-right" uk-icon="icon: shrink"></span>
                                На загрузке
                            </a>
                            </li>
                            <li><a class="uk-text-success" href="{% url "path-purchase-list" %}">
                                <span class="uk-margin-small-right" uk-icon="icon: shrink"></span>
                                Погружено
                            </a>
                            </li>
                            <li><a class="uk-text-primary" href="{% url "click-purchase-list" %}">
                                <span class="uk-margin-small-right" uk-icon="icon: shrink"></span>
                                Отметка в пути
                            </a>
                            </li>
                        </ul>
                    <li class="uk-nav-divider"></li>
                    </li>
                    <li class="uk-nav-divider"></li>
                    <li class="uk-parent">
                        <a class="uk-text-uppercase" href="#">
                            <span class="uk-margin-small-right" uk-icon="icon: expand"></span>
                            Работа с исходящими заявками
                        </a>
                        <ul class="uk-nav-sub">
                            <li class="uk-nav-divider"></li>
                            <li><a class="uk-text-danger" href="{% url "work-sale-list" %}">
                                <span class="uk-margin-small-right" uk-icon="icon: expand"></span>
                                Заявки в обработке
                            </a>
                            </li>
                            <li><a class="uk-text-warning" href="{% url "upload-sale-list" %}">
                                <span class="uk-margin-small-right" uk-icon="icon: expand"></span>
                                На загрузке
                            </a>
                            </li>
                            <li><a class="uk-text-success" href="{% url "path-sale-list" %}">
                                <span class="uk-margin-small-right" uk-icon="icon: expand"></span>
                                Погружено
                            </a>
                            </li>
                            <li><a class="uk-text-primary" href="{% url "click-sale-list" %}">
                                <span class="uk-margin-small-right" uk-icon="icon: expand"></span>
                                Отметка в пути
                            </a>
                            </li>
                        </ul>
                    </li>
                </ul>

            </li>

        </ul>

    </div>
</div>

templates/base/pagination.html
<ul class="uk-pagination">

        {% if page.has_previous %}
            <li>
            <a href="?page=1">&laquo; 1</a>
            </li>
            <li>
            <a href="?page={{ page.previous_page_number }}">предыдущая</a>
            </li>
        {% endif %}

        <li class="uk-active">
            Страниц {{ page.number }} из {{ page.paginator.num_pages }}.
        </li>

        {% if page.has_next %}
            <li>
            <a href="?page={{ page.next_page_number }}">следующая</a>
            </li>
            <li>
            <a href="?page={{ page.paginator.num_pages }}">{{ page.paginator.num_pages }} &raquo;</a>
            </li>
        {% endif %}
    </li>
</ul>

templates/base/paginator-list.html
<ul class="uk-pagination">

        {% if page_obj.has_previous %}
            <li>
            <a href="?page=1">&laquo; 1</a>
            </li>
            <li>
            <a href="?page={{ page_obj.previous_page_number }}">предыдущая</a>
            </li>
        {% endif %}

        <li class="uk-active">
            Страниц {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
        </li>

        {% if page_obj.has_next %}
            <li>
            <a href="?page={{ page_obj.next_page_number }}">следующая</a>
            </li>
            <li>
            <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }} &raquo;</a>
            </li>
        {% endif %}
    </li>
</ul>