app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from logistics.views import HomePageView

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('summernote/', include('django_summernote.urls')),
    path('', HomePageView.as_view(), name="home"),
    path('login/', include('login.urls')),
    path('sale/', include('sale.urls')),
    path('purchase/', include('purchase.urls')),
    path('handbook/', include('handbook.urls')),
    path('logistics/', include('logistics.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handbook/urls.py
from django.urls import path
from .views import *


urlpatterns = [
	path('out-path/', OutPathList.as_view(), name="out-path"),
	path('out-path/<int:pk>/', OutSort.as_view(), name="out-path-sort"),
	path('out-path-response/', out_response,),

	path('in-path/', InPathList.as_view(), name="in-path"),
	path('in-path/<int:pk>/', InSort.as_view(), name="in-path-sort"),
	path('in-path-response/', in_response,),

	path('city/', CityList.as_view(), name="city"),
	path('client/', ClientList.as_view(), name="client_list"),
	path('provider/', ProviderList.as_view(), name="provider"),
	path('status/', StatusList.as_view(), name="status"),
	path('cargo/', CargoList.as_view(), name="cargo"),
	path('trade-term/', TradeTermList.as_view(), name="trade-term"),
	path('transport/', TransportList.as_view(), name="transport"),
	path('currency/', CurrencyList.as_view(), name="currency"),
	path('path/', PathList.as_view(), name="path"),
	path('logistics-provider/', LogisticsProviderList.as_view(), name="logistics-provider"),

	path('edit/', ajax_data,)
]

handbook/models.py
import random

from django.db import models
from django.urls import reverse


class City(models.Model):
	"""города"""
	name = models.CharField(
		verbose_name="город",
		max_length=100,
		unique=True,
		default="city",
	)

	class Meta:
		verbose_name = "город"
		verbose_name_plural = "города"
		ordering = ['name']

	def get_absolute_url(self):
		reverse('city', kwargs={'pk': self.id})

	def __str__(self):
		return self.name

	def save(self, *args, **kwargs):
		self.name = self.name.upper()
		super(City, self).save(*args, **kwargs)


class OutPath(models.Model):
	"""номера маршрутов исходящего"""
	description = models.CharField(
		verbose_name="Описание маршрута",
		blank=False,
		max_length=100,
		default="UZ-?"
	)
	code_path = models.PositiveIntegerField(
		verbose_name="код маршрута",
		unique=True,
		null=True,
		blank=True
	)
	city = models.ManyToManyField(
		City,
		verbose_name="города",
		related_name="out_path"
	)
	date_input = models.DateField(
		verbose_name="Дата создания",
		auto_now_add=True,
		editable=False,
		null=True,
		blank=True
	)
	date_update = models.DateField(
		verbose_name="Дата обновления",
		auto_now=True,
		editable=False,
		null=True,
		blank=True
	)

	class Meta:
		verbose_name = "маршрут исходящий"
		verbose_name_plural = "маршруты исходящие"

	def __str__(self):
		return f"{self.code_path}/{self.description}"

	def save(self, *args, **kwargs):
		self.code_path = self.get_code()
		super(OutPath, self).save(*args, **kwargs)

	def get_absolute_url(self):
		return reverse('out-path-sort', kwargs={'pk': self.pk})

	def get_code(self):
		k = OutPath.objects.filter(id=self.id).exists()
		if k:
			return self.code_path
		else:
			r = random.randint(1, 10000)
			self.code_path = 100000 + r
			return self.code_path


class InPath(models.Model):
	"""Маршрут входящий"""
	description = models.CharField(
		verbose_name="Описание маршрута",
		blank=False,
		max_length=100,
		default="?-UZ"
	)
	city = models.ManyToManyField(
		City,
		verbose_name="города",
		related_name="in_path"
	)
	code_path = models.PositiveIntegerField(
		"код маршрута",
		unique=True,
		blank=True,
		editable=False,
	)
	date_input = models.DateField(
		verbose_name="Дата создания",
		auto_now_add=True,
		editable=False,
		null=True,
		blank=True
	)
	date_update = models.DateField(
		verbose_name="Дата обновления",
		auto_now=True,
		editable=False,
		null=True,
		blank=True
	)

	class Meta:
		verbose_name = "маршрут входящий"
		verbose_name_plural = "маршруты входящие"

	def __str__(self):
		return f"{self.code_path}/{self.description}"

	def save(self, *args, **kwargs):
		self.code_path = self.get_code()
		super(InPath, self).save(*args, **kwargs)

	def get_absolute_url(self):
		return reverse('in-path-sort', kwargs={'pk': self.pk})

	def get_code(self):
		k = InPath.objects.filter(id=self.id).exists()
		if k:
			return self.code_path
		else:
			r = random.randint(1, 10000)
			self.code_path = 100000 + r
			return self.code_path

	def get_transport(self):
		return InPathSort.objects.filter(path_code=self.code_path)


class Client(models.Model):
	"""клиент которому поставляется груз"""
	name = models.CharField(
		verbose_name="клиет",
		max_length=200,
		blank=False,
		null=False,
		default="client",
		unique=True
	)

	class Meta:
		verbose_name = "клиет"
		verbose_name_plural = "клиеты"
		ordering = ['name']

	def __str__(self):
		return self.name

	def save(self, *args, **kwargs):
		self.name = self.name.upper()
		super(Client, self).save(*args, **kwargs)


class Provider(models.Model):
	"""поставщик груза по заявкам от закупщиков"""
	name = models.CharField(
		verbose_name="поставщик",
		max_length=200,
		blank=False,
		null=False,
		default="provider",
		unique=True
	)

	class Meta:
		verbose_name = "поставщик"
		verbose_name_plural = "поставщики"
		ordering = ['name']

	def __str__(self):
		return self.name

	def save(self, *args, **kwargs):
		self.name = self.name.upper()
		super(Provider, self).save(*args, **kwargs)


class Status(models.Model):
	"""статусы"""
	name = models.CharField(
		"Статус",
		max_length=20,
		unique=True,
		blank=False,
		default="status",
		null=False
	)

	class Meta:
		verbose_name = "Статус"
		verbose_name_plural = "Статусы"
		ordering = ['id']

	def __str__(self):
		return self.name

	def save(self, *args, **kwargs):
		self.name = self.name.upper()
		super(Status, self).save(*args, **kwargs)


class Cargo(models.Model):
	"""название грузов"""
	name = models.CharField(
		"материал",
		max_length=200,
		blank=False,
		null=False,
		default="cargo",
		unique=True
	)

	class Meta:
		verbose_name = "материал"
		verbose_name_plural = "материалы"
		ordering = ['name']

	def __str__(self):
		return self.name

	def save(self, *args, **kwargs):
		self.name = self.name.upper()
		super(Cargo, self).save(*args, **kwargs)


class TradeTerm(models.Model):
	"""торговые термины"""
	name = models.CharField(
		verbose_name="торговы термин",
		max_length=10,
		null=False,
		blank=False,
		default="example"
	)

	class Meta:
		verbose_name = "торговый термин"
		verbose_name_plural = "торговые термины"
		ordering = ['name']

	def __str__(self):
		return self.name

	def save(self, *args, **kwargs):
		self.name = self.name.upper()
		super(TradeTerm, self).save(*args, **kwargs)


class Transport(models.Model):
	name = models.CharField(
		"Транспорт",
		max_length=20,
		unique=True,
		blank=False,
		null=False,
		default="example"
	)

	class Meta:
		verbose_name = "Транспорт"
		verbose_name_plural = "Транспорт"
		ordering = ['name']

	def __str__(self):
		return self.name

	def save(self, *args, **kwargs):
		self.name = self.name.upper()
		super(Transport, self).save(*args, **kwargs)


class OutPathSort(models.Model):
	"""сортировка городов в маршруте"""
	path_code = models.ForeignKey(
		OutPath,
		verbose_name="код исходящего маршрута",
		on_delete=models.CASCADE,
		related_name="out_path"
	)
	city = models.ForeignKey(City, verbose_name="города", on_delete=models.CASCADE)
	sort = models.PositiveSmallIntegerField(verbose_name="ключ сортировки")
	transport = models.ForeignKey(
		Transport,
		verbose_name="транспорт",
		on_delete=models.SET_NULL,
		blank=False,
		null=True,
	)

	class Meta:
		ordering = ['path_code', 'sort']
		verbose_name = "Сортировка по исходящему маршруту"
		verbose_name_plural = "Сортировка по исходящем маршрутам"

	def __str__(self):
		return f"{self.path_code}/{self.city}/{self.sort}"

	def city_out(self):
		count = OutPath.objects.get(pk=self.path_code)
		city_list = count.city.filter(city_name=count.pk)
		return city_list


class InPathSort(models.Model):
	path_code = models.ForeignKey(
		InPath,
		verbose_name="код входящего маршрута",
		on_delete=models.CASCADE,
		related_name="in_path"
	)
	city = models.ForeignKey(
		City,
		verbose_name="города",
		on_delete=models.CASCADE
	)
	sort = models.PositiveSmallIntegerField(verbose_name="ключ сортировки")
	transport = models.ForeignKey(
		Transport,
		verbose_name="транспорт",
		on_delete=models.SET_NULL,
		blank=False,
		null=True,
	)

	class Meta:
		ordering = ['path_code', 'sort']
		verbose_name = "Сортировка по входящему маршруту"
		verbose_name_plural = "Сортировка по входящим маршрутам"

	def __str__(self):
		return f"{self.path_code}/{self.city}/{self.sort}"

	def city_in(self):
		count = InPath.objects.get(pk=self.path_code)
		city_list = count.city.filter(city_name=count.pk)
		return city_list


class Currency(models.Model):
	name = models.CharField(verbose_name="Валюта", max_length=10, default="сум")

	class Meta:
		verbose_name = "Валюта"
		verbose_name_plural = "Валюты"
		ordering = ['name']

	def __str__(self):
		return self.name


class Path(models.Model):
	"""вид маршрута loc, imp, exp"""
	name = models.CharField(verbose_name="Вид", max_length=50)

	class Meta:
		verbose_name = "Вид"
		verbose_name_plural = "Виды"
		ordering = ['name']

	def __str__(self):
		return self.name


class LogisticsProvider(models.Model):
	"""поставщик услуг для логиста"""
	name = models.CharField(verbose_name="Поставщик услуг", max_length=50)

	class Meta:
		verbose_name = "Поставщик"
		verbose_name_plural = "Поставщики"
		ordering = ['name']

	def __str__(self):
		return self.name

handbook/forms.py
from django import forms
from .models import *


class OutPathForm(forms.ModelForm):
	city = forms.ModelMultipleChoiceField(
		queryset=City.objects.all(),
		widget=forms.CheckboxSelectMultiple,
		required=False,
		label="Города"
	)

	class Meta:
		model = OutPath
		exclude = ('date_input', 'date_update', 'code_path')


class InPathForm(forms.ModelForm):
	city = forms.ModelMultipleChoiceField(
		queryset=City.objects.all(),
		widget=forms.CheckboxSelectMultiple,
		required=False,
		label="Города"
	)

	class Meta:
		model = InPath
		exclude = ('date_input', 'date_update', 'code_path')


# class OutSortForm(forms.Form):
# 	path_code = forms.IntegerField(label="Код маршрута")
# 	city = forms.IntegerField(label="")
# 	class Meta:
# 		model = OutPathSort
# 		fields = ['path_code', 'city', 'sort']


class InSortForm(forms.ModelForm):

	class Meta:
		model = InPathSort
		fields = ['path_code', 'city', 'sort']

handbook/views.py
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.http import JsonResponse, response
from django.views.generic.base import View

from .forms import *
from .utils import *

from handbook.models import *


class OutPathList(PermissionRequiredMixin, ObjectDetailMixin2, View):
	"""получение списка, CRUD - OutPath"""
	model = OutPath
	template_name = 'handbook/path-list.html'
	url = "/handbook/out-path/"
	form_name = OutPathForm
	permission_required = 'handbook.add_outpath'
	login_url = 'login'


class InPathList(PermissionRequiredMixin, ObjectDetailMixin2, View):
	"""получение списка, CRUD - InPath"""
	model = InPath
	template_name = 'handbook/path-list.html'
	url = "/handbook/in-path/"
	form_name = InPathForm
	permission_required = 'handbook.add_inpath'
	login_url = 'login'


class InSort(PermissionRequiredMixin, ObjectDetailMixin3, View):
	"""получение списка, CRUD - InPath"""
	model = InPathSort
	extra_model = InPath
	template_name = 'handbook/path-sort.html'
	url = "/handbook/in-path-response/"
	permission_required = 'handbook.add_inpathsort'
	login_url = 'login'


class OutSort(PermissionRequiredMixin, ObjectDetailMixin3, View):
	"""получение списка, CRUD - InPath"""
	model = OutPathSort
	extra_model = OutPath
	template_name = 'handbook/path-sort.html'
	url = "/handbook/out-path-response/"
	permission_required = 'handbook.add_outpathsort'
	login_url = 'login'


@permission_required('handbook.add_outpath', login_url='/login/')
def out_response(request):
	pk = request.session['path_id']
	obj = OutPath.objects.get(pk=pk)
	url = obj.get_absolute_url
	template_name = 'handbook/response.html'
	city_list = OutPathSort.objects.filter(path_code=pk)
	city = city_list.exists()

	return render(request, template_name, {
		'obj': obj,
		"city_list": city_list,
		"city": city,
		"url": url
	})


@permission_required('handbook.add_inpath', login_url='/login/')
def in_response(request):
	pk = request.session['path_id']
	obj = InPath.objects.get(pk=pk)
	url = obj.get_absolute_url
	template_name = 'handbook/response.html'
	city_list = InPathSort.objects.filter(path_code=pk)
	city = city_list.exists()

	return render(request, template_name, {
		'obj': obj,
		"city_list": city_list,
		"city": city,
		"url": url
	})


class CityList(PermissionRequiredMixin, ObjectDetailMixin, View):
	"""получение списка, CRUD - city"""
	model = City
	template_name = 'handbook/list.html'
	url = "/handbook/city/"
	permission_required = 'handbook.add_city'
	login_url = 'login'


class ClientList(PermissionRequiredMixin, ObjectDetailMixin, View):
	"""получение списка, CRUD - Client"""
	model = Client
	template_name = 'handbook/list.html'
	url = "/handbook/client/"
	permission_required = 'handbook.add_client'
	login_url = 'login'


class ProviderList(PermissionRequiredMixin, ObjectDetailMixin, View):
	"""получение списка, CRUD - provider"""
	model = Provider
	template_name = 'handbook/list.html'
	url = "/handbook/provider/"
	permission_required = 'handbook.add_provider'
	login_url = 'login'


class CargoList(PermissionRequiredMixin, ObjectDetailMixin, View):
	"""получение списка, CRUD - cargo"""
	model = Cargo
	template_name = 'handbook/list.html'
	url = "/handbook/cargo/"
	permission_required = 'handbook.add_cargo'
	login_url = 'login'


class TradeTermList(PermissionRequiredMixin, ObjectDetailMixin, View):
	"""получение списка, CRUD - TradeTerm"""
	model = TradeTerm
	template_name = 'handbook/list.html'
	url = "/handbook/trade-term/"
	permission_required = 'handbook.add_tradeterm'
	login_url = 'login'


class StatusList(PermissionRequiredMixin, ObjectDetailMixin, View):
	"""получение списка, CRUD - status"""
	model = Status
	template_name = 'handbook/list.html'
	url = "/handbook/status/"
	permission_required = 'handbook.add_status'
	login_url = 'login'


class TransportList(PermissionRequiredMixin, ObjectDetailMixin, View):
	"""получение списка, CRUD - transport"""
	model = Transport
	template_name = 'handbook/list.html'
	url = "/handbook/transport/"
	permission_required = 'handbook.add_transport'
	login_url = 'login'


class CurrencyList(PermissionRequiredMixin, ObjectDetailMixin, View):
	"""получение списка, CRUD - Currency"""
	model = Currency
	template_name = 'handbook/list.html'
	url = "/handbook/currency/"
	permission_required = 'handbook.add_currency'
	login_url = 'login'


class PathList(PermissionRequiredMixin, ObjectDetailMixin, View):
	"""получение списка, CRUD - Path"""
	model = Path
	template_name = 'handbook/list.html'
	url = "/handbook/path/"
	permission_required = 'handbook.add_path'
	login_url = 'login'


class LogisticsProviderList(PermissionRequiredMixin, ObjectDetailMixin, View):
	"""получение списка, CRUD - Provider"""
	model = LogisticsProvider
	template_name = 'handbook/list.html'
	url = "/handbook/logistics-provider/"
	permission_required = 'handbook.add_path'
	login_url = 'login'


def ajax_data(request):
	if request.is_ajax():
		if request.GET.get('name') == 'inpath':
			req1 = InPathSort.objects.get(id=request.GET.get('id'))
			if request.GET.get('id') and request.GET.get('sort'):
				req1.sort = request.GET.get('sort')
				req1.save(update_fields=['sort'])
			elif request.GET.get('id') and request.GET.get('transport'):
				req1.transport_id = request.GET.get('transport')
				req1.save(update_fields=['transport'])
		else:
			req2 = OutPathSort.objects.get(id=request.GET.get('id'))
			if request.GET.get('id') and request.GET.get('sort'):
				req2.sort = request.GET.get('sort')
				req2.save(update_fields=['sort'])
			elif request.GET.get('id') and request.GET.get('transport'):
				req2.transport_id = request.GET.get('transport')
				req2.save(update_fields=['transport'])

		data = {
			'yes': True
		}
		return JsonResponse(data)

handbook/templates/handbook/path-list.html
{% extends 'base/index.html' %}
{% load static %}
{% load widget_tweaks %}
{% load my_tags %}

{% block title %}
{% for object in object_list %}
        {% if forloop.first %}
            {{ object|verbose_name_plural|upper }}
        {% else %}
        {% endif %}

    {% endfor %}
{% endblock %}

{% block main-content %}
    {% for object in object_list %}
        {% if forloop.first %}
            <h3>{{ object|verbose_name_plural|upper }}</h3>
        {% else %}
        {% endif %}

    {% endfor %}
    <button class="uk-button uk-button-default uk-margin-small-right" type="button" uk-toggle="target: #modal2">
        Добавить наименование
    </button>
    {% if info %}
        <div class="uk-alert-danger" uk-alert>
            <a class="uk-alert-close" uk-close></a>
            <h3>Ошибка</h3>
            <p>Не добвлено в базую. Возможно эта запись уже есть - {{ name|upper }}.</p>
        </div>
    {% endif %}
    <div class="uk-overflow-auto">
        <table class="uk-table uk-table-divider uk-table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>Код маршрута</th>
                <th>Города</th>
                <th>Изменить</th>
                <th>Удалить</th>
            </tr>
            </thead>
            <tbody>
            {% for object in object_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td class="uk-table-link"><a href="{{ object.get_absolute_url }}">{{ object }}</a></td>
                    <td>{% for city in object.city.all %}
                        {{ city }}
                    {% endfor %}</td>
                    <td>
                        <button uk-toggle="target: #update{{ object.id }}" class="uk-button uk-button-primary"
                                type="button">
                            <span class="uk-margin-small-right" uk-icon="pencil"></span>
                            Изменить
                        </button>
                    </td>
                    <td>
                        <button class="uk-button uk-button-danger" uk-toggle="target: #delete{{ object.id }}"
                                type="button">
                            <span class="uk-margin-small-right" uk-icon="trash"></span>
                            Удалить
                        </button>
                    </td>
                </tr>
            {% empty %}
                <h2 class="uk-margin-medium-top">Нет данных для вывода</h2>
            {% endfor %}
            </tbody>
        </table>

    </div>
    {% include "base/pagination.html" with page=object_list %}
{% endblock %}

{% block modal %}
    <div id="modal2" uk-modal>
        <div class="uk-modal-dialog uk-modal-body">
            <h3 class="uk-modal-title">Дабавление в справочник</h3>
            <form method="post">
                {% csrf_token %}
                <input type="hidden" value="1" name="create">
                <fieldset class="uk-fieldset">
                    <div class="uk-margin">
                        <label class="uk-form-label">
                            {{ form.description.label }}
                        </label>
                        <div class="uk-form-controls">
                            {{ form.description|add_class:"uk-select" }}
                        </div>
                    </div>

                    <div class="uk-margin">
                        <label class="uk-form-label">
                            {{ form.city.label }}
                        </label>
                        <div class="uk-margin uk-grid-small uk-child-width-auto uk-grid">
                            {% for c in form.city %}
                                <label>{{ c }}</label>
                            {% endfor %}
                        </div>
                    </div>

                    <p class="uk-text-right">
                        <button class="uk-button uk-button-default uk-modal-close" type="button">Отмена</button>
                        <button type="submit" class="uk-button uk-button-primary">Сохранить</button>
                    </p>
                </fieldset>
            </form>
        </div>
    </div>


    {% for object in object_list %}
    <div id="update{{ object.id }}" uk-modal>
        <div class="uk-modal-dialog uk-modal-body">
            <h3 class="uk-modal-title">Дабавление в справочник</h3>
            <form method="post">
                {% csrf_token %}
                <input type="hidden" value="{{ object.id }}" name="id">
                <input type="hidden" value="1" name="update">
                <fieldset class="uk-fieldset">
                    <div class="uk-margin">
                        <label class="uk-form-label">
                            {{ form.description.label }}
                        </label>
                        <div class="uk-form-controls">
                            <input class="uk-input" type="text" id="id_description" name="description" value="{{ object.description }}">
                        </div>
                    </div>

                    <div class="uk-margin">
                        <label class="uk-form-label">
                            {{ form.city.label }}
                        </label>
                        <div class="uk-margin uk-grid-small uk-child-width-auto uk-grid">
                            {% for c in form.city %}
                                <label>{{ c }}</label>
                            {% endfor %}
                        </div>
                    </div>

                    <p class="uk-text-right">
                        <button class="uk-button uk-button-default uk-modal-close" type="button">Отмена</button>
                        <button type="submit" class="uk-button uk-button-secondary">Обновить</button>
                    </p>
                </fieldset>
            </form>
        </div>
    </div>
    {% endfor %}

    {% for object in object_list %}
    <div id="delete{{ object.id }}" uk-modal>
        <div class="uk-modal-dialog uk-modal-body">
            <h3 class="uk-modal-title">Удаление маршрута</h3>
            <form method="post">
                {% csrf_token %}
                <input type="hidden" value="{{ object.id }}" name="id">
                <input type="hidden" value="1" name="delete">
                <fieldset class="uk-fieldset">
                    <div class="uk-margin">
                        <label class="uk-form-label">
                            {{ form.description.label }}
                        </label>
                        <div class="uk-form-controls">
                            <h4>{{ object}}</h4>
                        </div>
                    </div>
                    <p class="uk-text-right">
                        <button class="uk-button uk-button-default uk-modal-close" type="button">Отмена</button>
                        <button type="submit" class="uk-button uk-button-danger">Удалить</button>
                    </p>
                </fieldset>
            </form>
        </div>
    </div>
    {% endfor %}


{% endblock %}

handbook/templates/handbook/path-sort.html
{% extends 'base/index.html' %}
{% load static %}
{% load widget_tweaks %}
{% load my_tags %}
{% block title %}
Страница сортировки городов по маршруту {{ obj }}
{% endblock %}


{% block main-content %}

    <button class="uk-button uk-button-default uk-margin-small-right" type="button" uk-toggle="target: #modal2">
        Добавить сортировку
    </button>
    {% if info %}
        <div class="uk-alert-danger" uk-alert>
            <a class="uk-alert-close" uk-close></a>
            <h3>Ошибка</h3>
            <p>Не добвлено в базую. Возможно эта запись уже есть - {{ obj|upper }}.</p>
        </div>
    {% endif %}
    <div class="uk-overflow-auto">
        <table class="uk-table uk-table-divider uk-table-striped">
            <thead>
            <tr>
                <th>Код маршрута</th>
                <th>Города</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>{{ obj }}</td>
                <td>{% for city in obj.city.all %}
                    {{ city }}
                {% endfor %}</td>
            </tr>
            </tbody>
        </table>

        <div class="uk-overflow-auto">
            <table class="uk-table uk-table-divider uk-table-striped">
                <thead>
                <tr>
                    <th>Город</th>
                    <th>порядок</th>
                    <th>Изменить порядок</th>
                    <th>Транспорт</th>
                </tr>
                </thead>
                <tbody>
                {% for city in city_list %}
                    <tr>

                        <td>{{ city.city }}</td>
                        <td>
                            {{ city.sort }}
                        </td>
                        <td>
                            <form action="" method="get">
                                <input type="hidden" name="path_code" value="{{ city.path_code_id }}">
                                <input type="hidden" name="city" value="{{ city.city_id }}">
                                <select id="sort{{ city.city_id }}{{ city.path_code_id }}" class="uk-select uk-width-1-5" name="sort" value="{{ city.sort }}">
                                    {% for max in max_city %}
                                        <option value="{{ max }}">{{ max }}</option>
                                    {% endfor %}
                                    
                                </select>
                            <select id="transport{{ city.city_id }}{{ city.path_code_id }}" class="uk-select uk-width-1-5" name="transport" value="{{ city.transport }}">
                                    {% for t in transport %}
                                        <option value="{{ t.id }}">{{ t }}</option>
                                    {% endfor %}

                                </select>
                            </form>
                        </td>
                        <td>{{ city.transport }}</td>

                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

    </div>
{% endblock %}

{% block modal %}
    <div id="modal2" uk-modal>
        <div class="uk-modal-dialog uk-modal-body">
            <h3 class="uk-modal-title">Добавление сортировки</h3>
            <form method="post">
                {% csrf_token %}
                <fieldset class="uk-fieldset">

                    <input type="hidden" name="path_code" value="{{ obj.pk }}">
                    <div class="uk-margin">
                        <label class="uk-form-label">
                            Города
                        </label>
                        <div class="uk-margin">
                            <select name="city" id="id_city" class="uk-select">
                                {% for city in obj.city.all %}
                                    <option value="{{ city.id }}">{{ city }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    <div class="uk-margin">
                        <label class="uk-form-label">
                            Ключ сортировки
                        </label>
                        <div class="uk-margin">
                            <input type="text" class="uk-input" name="sort">
                        </div>
                    </div>
                    <div class="uk-margin">
                        <label class="uk-form-label">
                            Транспорт
                        </label>
                        <div class="uk-margin">
                            <select type="text" class="uk-select" name="transport">
                                {% for item in transport %}
                                    <option value="{{ item.id }}">{{ item }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    <p class="uk-text-right">
                        <button class="uk-button uk-button-default uk-modal-close" type="button">Отмена</button>
                        <button type="submit" class="uk-button uk-button-primary">Сохранить</button>
                    </p>
                </fieldset>
            </form>
        </div>
    </div>


{% endblock %}

{% block ajax %}
   {% for city in city_list %}

       $("#sort{{ city.city_id }}{{ city.path_code_id }}").change(function () {
       var sort = $(this).val();
            var id = {{ city.id }};
            var sort = $(this).val();
            var name = '{{ name }}';
            $.ajax({
               url: '/handbook/edit/',
               data: {
                        'id': id,
                        'sort': sort,
                        'name': name,
                    },
               dataType: 'json',
               success: function (data) {
                    if (data.yes) { alert("Обновите страницу! Порядок для {{ city.city }} изменён");}
                        }
               });

        });
       $("#transport{{ city.city_id }}{{ city.path_code_id }}").change(function () {
            var id = {{ city.id }};
            var transport = $(this).val();
            var name = '{{ name }}';
            console.log( 'id=' + id + '\n' + 'transport=' + transport );
                $.ajax({
                   url: '/handbook/edit/',
                   data: {
                            'id': id,
                            'transport': transport,
                            'name': name,
                        },
                   dataType: 'json',
                   success: function (data) {
                        if (data.yes) { alert("Обновите страницу! Транспорт для {{ city.city }} изменён");}
                            }
                });

        });
    {% endfor %}
{% endblock %}