app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from logistics.views import HomePageView

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('summernote/', include('django_summernote.urls')),
    path('', HomePageView.as_view(), name="home"),
    path('login/', include('login.urls')),
    path('sale/', include('sale.urls')),
    path('purchase/', include('purchase.urls')),
    path('handbook/', include('handbook.urls')),
    path('logistics/', include('logistics.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

logistics/urls.py
from django.urls import path, include
from logistics.views import *


purchase_url = [
	path('update/<int:pk>/', WorkPurchaseUpdate.as_view(), name="work-purchase-update"),
	path('create/<int:pk>/', WorkPurchaseCreate.as_view(), name="work-purchase-create"),
	path('delete/<int:pk>/', WorkPurchaseDeleteView.as_view(), name="work-purchase-delete"),
	path('list/', WorkPurchaseList.as_view(), name="work-purchase-list"),

	path('upload/update/<int:pk>/', UploadPurchaseUpdate.as_view(), name="upload-purchase-update"),
	path('upload/list/', UploadPurchaseList.as_view(), name="upload-purchase-list"),

	path('path/list/', OnPathPurchaseList.as_view(), name="path-purchase-list"),
	path('path/update/<int:pk>/', OnPathPurchaseUpdate.as_view(), name="path-purchase-update"),

	path('click/<int:pk>/', ClickPurchaseDetail.as_view(), name="city-click-purchase"),
	# path('click/update/<int:pk>/', ClickPurchaseUpdate.as_view(), name="click-purchase-update"),
	path('click/list/', ClickPurchaseList.as_view(), name="click-purchase-list"),

	path('status-list/', StatusPurchaseList.as_view(), name="status-purchase-list"),

	path('all-data/', all_data_purchase, name="all_data_purshase"),

	path('city/<int:pk>/', ajax_click_purchase, name="ajax_click_purchase"),
	path('city-load/<int:pk>/', ajax_purchase, name="ajax_purchase"),

]

sale_url = [
	path('update/<int:pk>/', WorkSaleUpdate.as_view(), name="work-sale-update"),
	path('create/<int:pk>/', WorkSaleCreate.as_view(), name="work-sale-create"),
	path('delete/<int:pk>/', WorkSaleDeleteView.as_view(), name="work-sale-delete"),
	path('list/', WorkSaleList.as_view(), name="work-sale-list"),

	path('upload/update/<int:pk>/', UploadSaleUpdate.as_view(), name="upload-sale-update"),
	path('upload/list/', UploadSaleList.as_view(), name="upload-sale-list"),

	path('path/list/', OnPathSaleList.as_view(), name="path-sale-list"),
	path('path/update/<int:pk>/', OnPathSaleUpdate.as_view(), name="path-sale-update"),

	path('click/<int:pk>/', ClickSaleDetail.as_view(), name="city-click-sale"),
	# path('click/update/<int:pk>/', ClickSaleUpdate.as_view(), name="click-sale-update"),
	path('click/list/', ClickSaleList.as_view(), name="click-sale-list"),

	path('status-list/', StatusSaleList.as_view(), name="status-sale-list"),
	path('all-data/', all_data_sale, name="all_data_sale"),

	path('city/<int:pk>/', ajax_click_sale, name="ajax_click_sale"),
	path('city-load/<int:pk>/', ajax_sale, name="ajax_sale"),
]

urlpatterns = [
	path('purchase/', include(purchase_url)),
	path('sale/', include(sale_url)),
	# path('csv-response/', unruly_passengers_csv,)
]

logistics/forms.py
from django import forms
from django.contrib.auth.models import User

from handbook.models import *
from logistics.models import WorkSale, StatusBidSale, StatusBidPurchase, WorkPurchase


class WorkSaleForm(forms.ModelForm):
	created_by = forms.ModelChoiceField(queryset=User.objects.all(), widget=forms.HiddenInput)
	bid = forms.ModelChoiceField(queryset=StatusBidSale.objects.all(), widget=forms.HiddenInput)
	trade_term = forms.ModelMultipleChoiceField(queryset=TradeTerm.objects.all(), label="Торговые термины")
	delivery_date = forms.IntegerField(label="Дни доставки")
	shipping_date = forms.DateField(label="Дата погрузки")
	price = forms.IntegerField(label="Цена")
	currency = forms.ModelChoiceField(queryset=Currency.objects.all(), label="Валюта")
	way = forms.ModelChoiceField(queryset=OutPath.objects.all(), label="Исходяший маршрут")
	path = forms.ModelChoiceField(queryset=Path.objects.all(), label="Вид")
	num = forms.CharField(widget=forms.HiddenInput, required=False)
	comment = forms.CharField(widget=forms.HiddenInput, required=False)
	provider = forms.ModelChoiceField(queryset=LogisticsProvider.objects.all(), label="Поставщик услуг", )
	delta_price = forms.IntegerField(widget=forms.HiddenInput, )

	provider.widget.attrs.update({'class': 'uk-select'})
	path.widget.attrs.update({'class': 'uk-select'})
	trade_term.widget.attrs.update({'class': 'uk-select'})
	way.widget.attrs.update({'class': 'uk-select'})
	delivery_date.widget.attrs.update({'class': 'uk-input'})
	price.widget.attrs.update({'class': 'uk-input'})
	currency.widget.attrs.update({'class': 'uk-select'})
	shipping_date.widget.attrs.update({'class': 'uk-input'})

	class Meta:
		model = WorkSale
		exclude = (
			'pub_date',
			'update_date'
		)


class WorkPurchaseForm(forms.ModelForm):
	created_by = forms.ModelChoiceField(queryset=User.objects.all(), widget=forms.HiddenInput)
	bid = forms.ModelChoiceField(queryset=StatusBidPurchase.objects.all(), widget=forms.HiddenInput)
	trade_term = forms.ModelMultipleChoiceField(queryset=TradeTerm.objects.all(), label="Торговые термины")
	delivery_date = forms.IntegerField(label="Дни доставки")
	shipping_date = forms.DateField(label="Дата погрузки")
	price = forms.IntegerField(label="Цена")
	currency = forms.ModelChoiceField(queryset=Currency.objects.all(), label="Валюта")
	way = forms.ModelChoiceField(queryset=InPath.objects.all(), label="Входяший маршрут")
	path = forms.ModelChoiceField(queryset=Path.objects.all(), label="Вид")
	num = forms.CharField(widget=forms.HiddenInput, required=False)
	comment = forms.CharField(widget=forms.HiddenInput, required=False)
	provider = forms.ModelChoiceField(queryset=LogisticsProvider.objects.all(), label="Поставщик услуг",)
	delta_price = forms.IntegerField(widget=forms.HiddenInput, )

	provider.widget.attrs.update({'class': 'uk-select'})
	path.widget.attrs.update({'class': 'uk-select'})
	trade_term.widget.attrs.update({'class': 'uk-select'})
	way.widget.attrs.update({'class': 'uk-select'})
	delivery_date.widget.attrs.update({'class': 'uk-input'})
	price.widget.attrs.update({'class': 'uk-input'})
	currency.widget.attrs.update({'class': 'uk-select'})
	shipping_date.widget.attrs.update({'class': 'uk-input'})

	class Meta:
		model = WorkPurchase
		exclude = (
			'pub_date',
			'update_date'
		)


class PubDateFilterForm(forms.Form):
	min_pub_date = forms.DateField(label='Дата подачи заявки \"c\"', required=False)
	max_pub_date = forms.DateField(label='до', required=False)
	status = forms.ModelChoiceField(queryset=Status.objects.all(), label='статус', required=False)

	min_pub_date.widget.attrs.update({'class': 'uk-input'})
	max_pub_date.widget.attrs.update({'class': 'uk-input'})
	status.widget.attrs.update({'class': 'uk-select'})


class DateFilterForm(forms.Form):
	min_pub_date = forms.DateField(label='Дата подачи заявки \"c\"', required=False)
	max_pub_date = forms.DateField(label='до', required=False)
	min_end_date = forms.DateField(label='Крайний срок \"c\"', required=False)
	max_end_date = forms.DateField(label='до', required=False)
	status = forms.ModelChoiceField(queryset=Status.objects.all(), label='статус', required=False)

	min_pub_date.widget.attrs.update({'class': 'uk-input'})
	max_pub_date.widget.attrs.update({'class': 'uk-input'})
	min_end_date.widget.attrs.update({'class': 'uk-input'})
	max_end_date.widget.attrs.update({'class': 'uk-input'})
	status.widget.attrs.update({'class': 'uk-select'})

logistics/views.py
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy, reverse
from django.views.generic import TemplateView, CreateView, ListView, UpdateView, DeleteView
from django.views.generic.base import View
from django.views.generic.edit import FormMixin

from handbook.models import InPathSort, OutPathSort
from logistics.forms import WorkSaleForm, WorkPurchaseForm, PubDateFilterForm, DateFilterForm
from logistics.models import WorkSale, StatusBidSale, OnUploadSale, WorkSaleDelete, OnPathSale, CityClickSale, \
    StatusBidPurchase, WorkPurchase, OnUploadPurchase, WorkPurchaseDelete, OnPathPurchase, CityClickPurchase
from logistics.utils import ObjectDetailMixin
from purchase.models import BidPurchase
from sale.models import BidSale


class HomePageView(PermissionRequiredMixin, TemplateView):
    """домашняя страница"""
    template_name = "home/home.html"
    permission_required = 'handbook.view_cargo'
    login_url = 'login'


class StatusSaleList(PermissionRequiredMixin, FormMixin, ListView):
    """модель статуса заявок - связывает отдел сбыта с отделом логистики"""
    model = StatusBidSale
    template_name = 'logistics/sale/statusbidsale_list.html'
    permission_required = 'logistics.view_statusbidsale'
    login_url = 'login'
    paginate_by = 20
    form_class = DateFilterForm
    ordering = ['-id']

    def get_queryset(self):
        object_list = self.model.objects.all()
        query = self.form_class(self.request.GET or None)
        if query.is_valid():
            if query.cleaned_data['min_pub_date'] \
                    and query.cleaned_data['max_pub_date'] \
                    and query.cleaned_data['min_end_date'] \
                    and query.cleaned_data['max_end_date'] \
                    and self.request.GET['status']:
                status = int(self.request.GET['status']) - 1
                object_list = object_list.filter(
                    Q(bid__pub_date__gte=query.cleaned_data['min_pub_date'])
                    & Q(bid__pub_date__lte=query.cleaned_data['max_pub_date'])
                    & Q(bid__end_date__gte=query.cleaned_data['min_end_date'])
                    & Q(bid__end_date__lte=query.cleaned_data['max_end_date'])
                    & Q(status=status)
                )

            elif query.cleaned_data['max_pub_date'] \
                    and query.cleaned_data['max_end_date'] \
                    and query.cleaned_data['min_end_date'] \
                    and self.request.GET['status']:
                status = int(self.request.GET['status']) - 1
                object_list = object_list.filter(
                    Q(bid__pub_date__lte=query.cleaned_data['max_pub_date'])
                    & Q(bid__end_date__lte=query.cleaned_data['max_end_date'])
                    & Q(bid__end_date__gte=query.cleaned_data['min_end_date'])
                    & Q(status=status)
                )

            elif query.cleaned_data['min_pub_date'] \
                    and query.cleaned_data['max_end_date'] \
                    and query.cleaned_data['min_end_date'] \
                    and self.request.GET['status']:
                status = int(self.request.GET['status']) - 1
                object_list = object_list.filter(
                    Q(bid__pub_date__gte=query.cleaned_data['min_pub_date'])
                    & Q(bid__end_date__lte=query.cleaned_data['max_end_date'])
                    & Q(bid__end_date__gte=query.cleaned_data['min_end_date'])
                    & Q(status=status)
                )

            elif query.cleaned_data['min_pub_date'] \
                    and query.cleaned_data['max_pub_date'] \
                    and query.cleaned_data['min_end_date'] \
                    and self.request.GET['status']:
                status = int(self.request.GET['status']) - 1
                object_list = object_list.filter(
                    Q(bid__pub_date__gte=query.cleaned_data['min_pub_date'])
                    & Q(bid__pub_date__lte=query.cleaned_data['max_pub_date'])
                    & Q(bid__end_date__gte=query.cleaned_data['min_end_date'])
                    & Q(status=status)
                )

            elif query.cleaned_data['min_pub_date'] \
                    and query.cleaned_data['max_pub_date'] \
                    and query.cleaned_data['max_end_date'] \
                    and self.request.GET['status']:
                status = int(self.request.GET['status']) - 1
                object_list = object_list.filter(
                    Q(bid__pub_date__gte=query.cleaned_data['min_pub_date'])
                    & Q(bid__pub_date__lte=query.cleaned_data['max_pub_date'])
                    & Q(bid__end_date__lte=query.cleaned_data['max_end_date'])
                    & Q(status=status)
                )

            elif query.cleaned_data['min_pub_date'] \
                    and query.cleaned_data['max_pub_date'] \
                    and query.cleaned_data['max_end_date'] \
                    and query.cleaned_data['min_end_date']:
                object_list = object_list.filter(
                    Q(bid__pub_date__gte=query.cleaned_data['min_pub_date'])
                    & Q(bid__pub_date__lte=query.cleaned_data['max_pub_date'])
                    & Q(bid__end_date__gte=query.cleaned_data['min_end_date'])
                    & Q(bid__end_date__lte=query.cleaned_data['max_end_date'])
                )

            elif query.cleaned_data['min_pub_date'] \
                    and query.cleaned_data['max_end_date'] \
                    and query.cleaned_data['min_end_date']:
                object_list = object_list.filter(
                    Q(bid__pub_date__gte=query.cleaned_data['min_pub_date'])
                    & Q(bid__end_date__gte=query.cleaned_data['min_end_date'])
                    & Q(bid__end_date__lte=query.cleaned_data['max_end_date'])
                )

            elif query.cleaned_data['max_pub_date'] \
                    and query.cleaned_data['max_end_date'] \
                    and query.cleaned_data['min_end_date']:
                object_list = object_list.filter(
                    Q(bid__pub_date__lte=query.cleaned_data['max_pub_date'])
                    & Q(bid__end_date__gte=query.cleaned_data['min_end_date'])
                    & Q(bid__end_date__lte=query.cleaned_data['max_end_date'])
                )

            elif query.cleaned_data['min_end_date'] \
                    and query.cleaned_data['max_end_date'] \
                    and self.request.GET['status']:
                status = int(self.request.GET['status']) - 1
                object_list = object_list.filter(
                    Q(bid__end_date__gte=query.cleaned_data['min_end_date'])
                    & Q(bid__end_date__lte=query.cleaned_data['max_end_date'])
                    & Q(status=status)
                )

            elif query.cleaned_data['min_pub_date'] \
                    and query.cleaned_data['max_pub_date'] \
                    and self.request.GET['status']:
                status = int(self.request.GET['status']) - 1
                object_list = object_list.filter(
                    Q(bid__pub_date__gte=query.cleaned_data['min_pub_date'])
                    & Q(bid__pub_date__lte=query.cleaned_data['max_pub_date'])
                    & Q(status=status)
                )

            elif query.cleaned_data['min_end_date'] and self.request.GET['status']:
                status = int(self.request.GET['status']) - 1
                object_list = object_list.filter(
                    Q(bid__end_date__gte=query.cleaned_data['min_end_date'])
                    & Q(status=status)
                )

            elif query.cleaned_data['max_end_date'] and self.request.GET['status']:
                status = int(self.request.GET['status']) - 1
                object_list = object_list.filter(
                    Q(bid__end_date__lte=query.cleaned_data['max_end_date'])
                    & Q(status=status)
                )

            elif query.cleaned_data['min_pub_date'] and self.request.GET['status']:
                status = int(self.request.GET['status']) - 1
                object_list = object_list.filter(
                    Q(bid__pub_date__gte=query.cleaned_data['min_pub_date'])
                    & Q(status=status)
                )

            elif query.cleaned_data['max_pub_date'] and self.request.GET['status']:
                status = int(self.request.GET['status']) - 1
                object_list = object_list.filter(
                    Q(bid__pub_date__lte=query.cleaned_data['max_pub_date'])
                    & Q(status=status)
                )
            elif query.cleaned_data['min_end_date']:
                object_list = object_list.filter(
                    bid__end_date__gte=query.cleaned_data['min_end_date']
                )

            elif query.cleaned_data['max_end_date']:
                object_list = object_list.filter(
                    bid__end_date__lte=query.cleaned_data['max_end_date']
                )
            elif query.cleaned_data['min_pub_date']:
                object_list = object_list.filter(
                    bid__pub_date__gte=query.cleaned_data['min_pub_date']
                )

            elif query.cleaned_data['max_pub_date']:
                object_list = object_list.filter(
                    bid__pub_date__lte=query.cleaned_data['max_pub_date']
                )
            elif query.cleaned_data['status']:
                status = int(self.request.GET['status']) - 1
                object_list = object_list.filter(status=status)
            return object_list

logistics/templates/logistics/all_data_purchase.html
{% extends 'base/index.html' %}
{% load static %}
{% load my_tags %}

{% block title %}
    Итоговая таблица {% if mark %}
    входящих заявок
{% else %}
    исходящих заявок
{% endif %}
{% endblock %}

{% block main-content %}
    <h3>Итоговая таблица {% if mark %}
        входящих заявок
    {% else %}
        исходящих заявок
    {% endif %} </h3>

    <button class="uk-button uk-button-default uk-margin" id="excel">Скачать</button>
    <script src="{% static "/js/jquery2.min.js" %}"></script>
    <script src="{% static "/js/jquery.table2excel.min.js" %}"></script>
    <script type="text/javascript">
        $('#excel').click(function () {
            $(document).ready(function () {
                $("#exTable").table2excel({
                    filename: "Employees.xls"
                });
            });

        });
    </script>
    <form action="" method="GET">
        <div class="uk-fieldset" uk-grid>
            {% csrf_token %}
            {% for field in form_pub %}
                {% if field.is_hidden %}
                    {{ field }}
                {% else %}
                    <div class="uk-margin">
                        <label class="uk-form-label">
                            {{ field.label }}
                        </label>
                        <div class="uk-form-controls">

                            {% if field.errors %}
                                <div class="uk-alert-danger">
                                    {{ field.errors }}
                                </div>
                            {% endif %}

                            {{ field }}
                        </div>
                    </div>
                {% endif %}

            {% endfor %}
        </div>
        <div class="uk-margin">
            <input class="uk-button uk-button-default" value="Отправить" type="submit">
        </div>
        <script>
            flatpickr("#id_min_pub_date", {
                altInput: true,
                altFormat: "F j, Y",
                dateFormat: "Y-m-d",
                "locale": "ru",
            });
            flatpickr("#id_max_pub_date", {
                altInput: true,
                altFormat: "F j, Y",
                dateFormat: "Y-m-d",
                "locale": "ru",
            });
        </script>
    </form>
    <div class="uk-overflow-auto">
        <table class="uk-table uk-table-divider uk-table-striped uk-table-hover" id="exTable">
            <thead>
            <tr>
                <th class="uk-table-link">№ заявки</th>
                <th>Вид</th>
                <th>Материал</th>
                <th>№ заказа</th>
                <th>Торговые термины</th>
                <th>название маршрута</th>
                <th>Клиент/поставщик</th>
                <th>Статус</th>
                <th>Дата подачи заявки</th>
                <th>Дата принятия заявки в обработку</th>
                <th>дата начала пути</th>
                <th>дата окончания пути</th>
                {% if perms.logistics.add_cityclickpurchase %}
                    <th>Гос номер авто</th>
                    <th>Поставщик услуг</th>
                    <th>Цена услуги+доп дебеты</th>
                    <th>Итоговый комментарий</th>
                {% endif %}
            </tr>
            </thead>
            <tbody>
            {% for bid in object_list %}
                {% if bid.status == 4 %}
                    <tr style="background-color: greenyellow">
                        <td><a href="{% url 'work-purchase-update' bid.statuspurchase.pk %}">{{ bid.bid_id }}</a>
                        </td>
                        <td>
                            {{ bid.statuspurchase.path }}
                        </td>
                        <td>
                            {% for cargo in bid.bid.cargo.all %}
                                {{ cargo }}
                            {% endfor %}
                        </td>

                        <td>{{ bid.bid.bid_number }}</td>
                        <td>
                            {% for trade_term in bid.statuspurchase.trade_term.all %}
                                {{ trade_term }}
                            {% endfor %}
                        </td>
                        <td>{{ bid.statuspurchase.way.description }}</td>
                        <td>{{ bid.bid.client }}</td>
                        <td>
                            {% if bid.status == 1 %}
                                <span class="uk-text-warning">принята</span>
                            {% elif bid.status == 2 %}
                                <span class="uk-text-success">на загрузке</span>
                            {% elif bid.status == 3 %}
                                <span class="uk-text-primary">в пути</span>
                            {% elif bid.status == 4 %}
                                <span>закрыта</span>
                            {% else %}
                                <span class="uk-text-danger">не принята</span>
                            {% endif %}
                        </td>
                        <td>{{ bid.bid.pub_date }}</td>


                        <td>{{ bid.statuspurchase.pub_date }}</td>
                        <td>{{ bid.statuspurchase.cityonpathpurchase.pub_date }}</td>
                        <td>
                            {% if bid.status == 4 %}
                                {{ bid.statuspurchase.cityonpathpurchase.update_date }}
                            {% endif %}
                        </td>
                        {% if perms.logistics.add_cityclickpurchase %}
                            <td>{{ bid.statuspurchase.num }}
                            </td>
                            <td>
                                {{ bid.statuspurchase.provider }}
                            </td>
                            <td>{{ bid.statuspurchase.price }}/{{ bid.statuspurchase.delta_price }} {{ bid.statuspurchase.currency }}</td>
                            <td>{{ bid.statuspurchase.comment }}</td>
                        {% endif %}
                    </tr>
                {% else %}
                    <tr>
                        <td>
                            {% if bid.status %}
                                <a href="{% url 'work-purchase-update' bid.statuspurchase.pk %}">{{ bid.bid_id }}</a>
                                {% else %}
                                {{ bid.bid_id }}
                            {% endif %}

                        </td>
                        <td>
                            {{ bid.statuspurchase.path }}
                        </td>
                        <td>
                            {% for cargo in bid.bid.cargo.all %}
                                {{ cargo }}
                            {% endfor %}
                        </td>

                        <td>{{ bid.bid.bid_number }}</td>
                        <td>
                            {% for trade_term in bid.statuspurchase.trade_term.all %}
                                {{ trade_term }}
                            {% endfor %}
                        </td>
                        <td>{{ bid.statuspurchase.way.description }}</td>
                        <td>{{ bid.bid.client }}</td>
                        <td>
                            {% if bid.status == 1 %}
                                <span class="uk-text-success">принята</span>
                            {% elif bid.status == 2 %}
                                <span class="uk-text-success">на загрузке</span>
                            {% elif bid.status == 3 %}
                                <span class="uk-text-success">в пути</span>
                            {% elif bid.status == 4 %}
                                <span>закрыта</span>
                            {% else %}
                                <span class="uk-text-danger">не принята</span>
                            {% endif %}
                        </td>
                        <td>{{ bid.bid.pub_date }}</td>


                        <td>{{ bid.statuspurchase.pub_date }}</td>
                        <td>{{ bid.statuspurchase.cityonpathpurchase.pub_date }}</td>
                        <td>
                            {% if bid.status == 4 %}
                                {{ bid.statuspurchase.cityonpathpurchase.update_date }}
                            {% endif %}
                        </td>
                        {% if perms.logistics.add_cityclickpurchase %}
                            <td>{{ bid.statuspurchase.num }}
                            </td>
                            <td>
                                {{ bid.statuspurchase.provider }}
                            </td>
                            <td>{{ bid.statuspurchase.price }}/{{ bid.statuspurchase.delta_price }} {{ bid.statuspurchase.currency }}</td>
                            <td>{{ bid.statuspurchase.comment }}</td>
                        {% endif %}
                    </tr>
                {% endif %}
            {% empty %}
                Нет данных
            {% endfor %}
            </tbody>
        </table>
    </div>
    {% include "base/pagination.html" with page=object_list %}

{% endblock %}